### ISSUE TITLE
demo中PictureUploadView无法显示照片

### ISSUE THREAD

**Issue by yaojunyi** [sdwfqin/AndroidQuick#4]
我的手机android 10 
无论拍照还是从相册选择照片,最终显示的都是R.mipmap.image_load_err
跟踪了代码 传入ImageLoader.setImagePath()得到的是正确的路径
这是其中一张图片的地址:
/storage/emulated/0/DCIM/Camera/IMG_20200417_083929.jpg

**Comment by yaojunyi** [comment]
权限都是允许的,我检查了手机的权限设置页面

**Comment by sdwfqin** [comment]
因为Android 10 存储机制变更导致的，改为uri就可以了，相关代码已提交，感谢反馈！
