### ISSUE TITLE
九宫格选择图片后,显示的是R.mipmap.image_load_err

### ISSUE THREAD

**Issue by yaojunyi** [sdwfqin/AndroidQuick#5]
android 10,
运行你的项目代码,在PictureUploadActivity页面选择完相册图片后返回到PictureUploadActivity,图片显示的是PictureUploadAdapter中imageloader定义的setErrorImage(R.mipmap.image_load_err)

**Comment by sdwfqin** [comment]
请看 #4 因为Android 10 存储机制变更导致的，改为uri就可以了

**Comment by sdwfqin** [comment]
或者是尝试关闭沙盒化存储试一下

**Comment by yaojunyi** [comment]
好的 问题解决了 
使用Matisse.obtainResult得到List<Uri>,其中每个uri是个content协议的地址
