### ISSUE TITLE
搞个拍照预览的

### ISSUE THREAD

**Issue by Knight-xiaolu** [sdwfqin/AndroidQuick#7]
老弟搞个拍照预览  用cameraX遇到个问题 显示的图片被旋转了 关键只在部分手机上有问题 小米8

**Comment by sdwfqin** [comment]
老哥，我让朋友测试了demo里面的cameraX拍照跟拍完照的照片方向说是正常的，你那边具体是啥问题啊

**Comment by Knight-xiaolu** [comment]
拍照旋转了。。用的cameraX就小米8有问题。。不要用全屏

**Comment by sdwfqin** [comment]
我更新了一点代码你可以看看有没有用，我手上没有小米8，你可以debug一下OrientationEventListener看看
