### ISSUE TITLE
请添加一个扫描二维码的功能

### ISSUE THREAD

**Issue by yinanwang1** [sdwfqin/AndroidQuick#9]
CameraX的拍照功能是可以正常使用，但是想支持扫描二维码，一直失败，不知道是什么地方没有设置对。请新增一个扫码二维码，条形的功能吧。

**Comment by sdwfqin** [comment]
添加了一个简单示例，仅供参考，后期有时间可能会正式加一下这个功能。

**Comment by yinanwang1** [comment]
666
